account: nvr_elm_llm
cluster: cs
partition: polar3,polar,grizzly,polar4
time: 04:00:00
num_nodes: 1
job_name: t2i_image_generation
gpus_per_node: 1
exclusive: false
cpus_per_task: 12
mem_per_cpu: 16G
container_image: null
container_mounts: null
container_mount_home: false
pre_cmd: null
first_task_id: 0
last_task_id: 0
max_running_tasks: 64
global_batch_size: 0
eval_global_batch_size: 1
run_dir: exp_wenkunh/supir/4k_cs
interactive: true
only_print_script: false
only_generate_script: false
entrance: .supir_launcher
task_id: 0
prompt_dir: 1k
save_dir: 4k
num_jsons_per_task: 1
range_id: 0
num_samples_per_range: 70
